add Granulate gMaestro Addon
aws-samples/cdk-eks-blueprints-patterns pull request #101
Opened 2023-06-18 17:42 UTC by marina-vrublevsky

*Issue #, if available:*

*Description of changes:*
This PR continues https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/57

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-19 14:58 UTC, elamaran11 reviewed
@marina-vrublevsky Nice work on the patterns update. documentation file is missing like other patterns. Also details like secret should be removed in home `readme.md` file but rather should point to documentation
Also please share us the secret to validate this pattern in relevant AWS channel or POCs so we can consume to validate the pattern.

2023-06-19 14:58 UTC, elamaran11 commented on README.md
> +For `GmaestroConstruct` the pattern relies on the following secret defined, please see [Gmaestro documentation](https://github.com/Granulate/gmaestro-eks-blueprints-addon/blob/master/README.md):
You need a separate `md` file for Granulate like the other patterns you see. The pattern should clear have a complete documentation on how to deploy this pattern with all details, screenshots, diagram etc like example Kubeflow, Instana etc. You can add these details like secrets there.

2023-06-27 09:05 UTC, marina-vrublevsky commented on bin/gmaestro.ts
> +    errorHandler(app, "Gmaestro is not setup due to missing secrets: " + error);
Looks like the rest of them to me. e.g: `bin/instana-operator.ts`
Am i missing anything?

2023-06-27 10:09 UTC, marina-vrublevsky commented
@elamaran11 please rereview
> Also please share us the secret to validate this pattern in relevant AWS channel or POCs so we can consume to validate the pattern.

will be provided soon

2023-06-27 15:13 UTC, elamaran11 reviewed
Thankyou for your work on this PR, appreciate it. Have couple of minor comments if you can fix. Once you fix these, please share access to SAAS for validation.

2023-06-27 15:13 UTC, elamaran11 commented on bin/gmaestro.ts
> +    errorHandler(app, "Gmaestro is not setup due to missing secrets: " + error);
Looks good

2023-06-27 15:13 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +3. Create a secret (as a plaintext) in AWS Secrets Manager copy its value from the following place:
We should have a better mechanism to show to customer on how create secrets using CLI commands and also how to pass them to the solution. You should be using context to pass on fields mentioned below. Please see [this](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/instana.md) pattern for an example.

2023-06-27 15:13 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +- `createNamespace: boolean` - If you want CDK to create the namespace for you
We should create this in a new namespace, we should avoid default namespace usage and not a good practice to show in patterns for customers. You can use `createNamespace` field.

2023-06-27 15:16 UTC, elamaran11 commented
@marina-vrublevsky Please fix the above issues pointed out.

2023-08-04 18:55 UTC, elamaran11 commented
@marina-vrublevsky Please provide an update on this PR and Patterns Repo PR.

2023-08-30 12:52 UTC, elamaran11 commented
@freschri As discussed, please pick this PR for tech validation. @marina-vrublevsky Please share the secrets for your share platform to us in some secured manner (you can email us or let us know we can invite you to AWS Dev slack).

2023-08-31 08:59 UTC, marina-vrublevsky commented
@elamaran11 where can i email the secret?

2023-08-31 11:46 UTC, elamaran11 commented
> @elamaran11 where can i email the secret?

@marina-vrublevsky Share me your email, i will invite you to a slack workspace where you can share the secrets directly.

2023-08-31 14:12 UTC, elamaran11 commented
> @elamaran11 [marina.vrublevsky@granulate.io](mailto:marina.vrublevsky@granulate.io)

Hope you received the invite from Riccardo. Please share the secrets with him and myself in Slack.

2023-09-04 11:20 UTC, freschri approved these changes
approving following discussion on other channel and following amendments

2023-09-05 13:39 UTC, elamaran11 requested changes
@marina-vrublevsky Nice work on the pattern, almost there. Couple of comments to close the loop with the PR to close all gaps. Also `mkdocs.yml` file update is missing, we need this so that website publishing is also taken care after merge.

2023-09-05 13:39 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +2. Download a sample YAML file - After signing up to gMaestro, navigate to the [Deploy](https://app.granulate.io/deploy) on the left-hand menu, fill in the required fields and click on "Generate Conf
same feedback as addon. Either attach a download hyperlink or add the same below. Screenshot wont help people to code this sample.

2023-09-05 13:39 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +    aws secretsmanager create-secret --name <MAESTRO_SECRET_NAME> \
You are missing `region` parameter!

2023-09-05 13:39 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +
Please add a couple of screenshot to show gMaestro in action with visibility and how you can right size...

2023-09-05 13:39 UTC, elamaran11 commented on docs/patterns/gmaestro.md
> +If you have questions about Gmaestro, catch us [on Slack](https://granulatecommunity.slack.com/archives/C03RK0HN2TU)!
This is very nice!

2023-09-05 13:39 UTC, elamaran11 commented on package.json
>      "@aws-quickstart/eks-blueprints": "1.10.1",
Please reference the latest blueprints version in both places in `package.json`

2023-09-05 13:39 UTC, elamaran11 commented on README.md
> +For `GmaestroConstruct` the pattern relies on the following secret defined:
In this file `make list` command should be refreshed to show all patterns.

2023-09-05 14:28 UTC, marina-vrublevsky commented on package.json
>      "@aws-quickstart/eks-blueprints": "1.10.1",
what is the second place?

2023-09-05 15:36 UTC, elamaran11 approved these changes
LGTM

2023-09-05 15:38 UTC, elamaran11 commented
@freschri Can you confirm in this PR, you were able to complete the test pattern with provided credentials from the Partner and validation worked fine?

2023-09-05 15:40 UTC, elamaran11 commented
@marina-vrublevsky I see some GH action failures

2023-09-05 16:51 UTC, elamaran11 requested changes
@marina-vrublevsky See this comment for fixing the GH Action issue.

2023-09-05 16:51 UTC, elamaran11 commented on package.json
> +    "@aws-quickstart/eks-blueprints": "1.11.0",
Change this to latest patch version

2023-09-05 16:51 UTC, elamaran11 commented on package.json
> +    "@aws-quickstart/eks-blueprints": "1.11.0",
Change this to latest patch version

2023-09-05 16:51 UTC, elamaran11 commented on lib/gmaestro-construct/index.ts
> +            .region(process.env.CDK_DEFAULT_REGION)
.version('auto')

2023-09-05 18:22 UTC, elamaran11 commented
@marina-vrublevsky Apologies, looks like there is some breaking changes to latest version. Can. you go back to previous version of blueprints and aws-cdk and remove `.version('auto')`. We can merge this PR and then i can work on fixing the breaking change with latest version.

2023-09-05 18:39 UTC, marina-vrublevsky commented
> Can. you go back to previous version of blueprints 

which version? @elamaran11

2023-09-05 18:41 UTC, marina-vrublevsky commented
@elamaran11 reverted to the version from main branch

2023-09-05 18:52 UTC, elamaran11 commented
> @elamaran11 reverted to the version from main branch
Blueprints version. I saw you had handled it.

2023-09-05 19:03 UTC, elamaran11 approved these changes
LGTM

2023-09-05 19:04 UTC, merged