added AWS_REGION and updated gitOwner
aws-samples/cdk-eks-blueprints-patterns pull request #125
Opened 2023-07-14 23:11 UTC by iamprakkie

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-16 18:47 UTC, elamaran11 requested changes
@iamprakkie Thanks for doing this. Have some doc feedback. I see numbering is mis aligned. Also you can improve the doc with proper aws command as pointed out.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Configuring GitOps tooling (ArgoCD addon) to support deployment of [ho11y](https://github.com/aws-observability/aws-o11y-recipes/tree/main/sandbox/ho11y) and [yelb](https://github.com/mreferre/yel
Why did you remove the numbering. Why is all 1. 1.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Setting Amazon Managed Grafana to visualize AMP metrics from Amazon EKS cluster in Prod account 1 and CloudWatch metrics on workloads in Amazon EKS cluster in Prod account 2.
Im not really getting what is the change here except adding a line break.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. An AWS account under AWS Control Tower called Prod 1 Account(Workloads Account A aka prodEnv1) provisioned using the AWS Service Catalog Account Factory product AWS Control Tower Account vending p
Same comment numbering is lost and only change is adding line breaks

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `github-ssh-key` in `AWS_REGION` of `pipelineEnv` account. This secret must contain GitHub SSH private key as a JSON structure containing fields `sshPrivateKey` and `url` in `pipelin
Im not happy with numbering. Since you trying to make this better. Can you add a `aws secrets manager` command ?

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Create `github-token` secret in `AWS_REGION` of `pipelineEnv` account. This secret must be stored as a plain text in AWS Secrets Manager for the GitHub pipeline in `pipelineEnv` account. For more
Same, it will good if you can provide a direct command.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `cdk-context` in `us-east-1` region as a plain text in AWS Secrets Manager for the GitHub pipeline in `pipelineEnv` account. `cdk-context` secret must be stored as a plain text in th
Same provide a aws cli command.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +    1. IAM user `prod2-admin` with `administrator` in Prod 2 AWS Account
Same command numbering is lost and you added line break. Also considering replacing this with `aws cli` command to make it more meaningful.

2023-07-16 18:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Bootstrap all 4 AWS accounts using step mentioned for **different environment for deploying CDK applications** in [Deploying Pipelines](https://aws-quickstart.github.io/cdk-eks-blueprints/pipeline
probably since you were unclear, others will be too. lets add commands here.

2023-07-17 15:14 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Configuring GitOps tooling (ArgoCD addon) to support deployment of [ho11y](https://github.com/aws-observability/aws-o11y-recipes/tree/main/sandbox/ho11y) and [yelb](https://github.com/mreferre/yel
Using 1. for all numbering, will adapt continuity. In this way, if there is a need to add new steps in between, you don't have to update all numbers. I've used this numbering in MD previously and also verified here.

2023-07-17 15:14 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. An AWS account under AWS Control Tower called Prod 1 Account(Workloads Account A aka prodEnv1) provisioned using the AWS Service Catalog Account Factory product AWS Control Tower Account vending p
Using 1. for all numbering, will adapt continuity. In this way, if there is a need to add new steps in between, you don't have to update all numbers. I've used this numbering in MD previously and also verified here.

2023-07-17 15:14 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `github-ssh-key` in `AWS_REGION` of `pipelineEnv` account. This secret must contain GitHub SSH private key as a JSON structure containing fields `sshPrivateKey` and `url` in `pipelin
Using 1. for all numbering, will adapt continuity. In this way, if there is a need to add new steps in between, you don't have to update all numbers. I've used this numbering in MD previously and also verified here. 

Yes. Will add CLI command for secrets manager.

2023-07-17 15:15 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `cdk-context` in `us-east-1` region as a plain text in AWS Secrets Manager for the GitHub pipeline in `pipelineEnv` account. `cdk-context` secret must be stored as a plain text in th
Sure.

2023-07-17 16:47 UTC, elamaran11 requested changes

2023-07-17 16:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Configuring GitOps tooling (ArgoCD addon) to support deployment of [ho11y](https://github.com/aws-observability/aws-o11y-recipes/tree/main/sandbox/ho11y) and [yelb](https://github.com/mreferre/yel
Good to know.

2023-07-17 16:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. Setting Amazon Managed Grafana to visualize AMP metrics from Amazon EKS cluster in Prod account 1 and CloudWatch metrics on workloads in Amazon EKS cluster in Prod account 2.
Good to know.

2023-07-17 16:47 UTC, elamaran11 commented on docs/patterns/multi-account-monitoring.md
> +1. An AWS account under AWS Control Tower called Prod 1 Account(Workloads Account A aka prodEnv1) provisioned using the AWS Service Catalog Account Factory product AWS Control Tower Account vending p
SG

2023-07-17 19:08 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `github-ssh-key` in `AWS_REGION` of `pipelineEnv` account. This secret must contain GitHub SSH private key as a JSON structure containing fields `sshPrivateKey` and `url` in `pipelin
added CLI commands for secretsmanager

2023-07-17 19:08 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Create secret `cdk-context` in `us-east-1` region as a plain text in AWS Secrets Manager for the GitHub pipeline in `pipelineEnv` account. `cdk-context` secret must be stored as a plain text in th
added CLI commands for secretsmanager

2023-07-17 19:09 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +    1. IAM user `prod2-admin` with `administrator` in Prod 2 AWS Account
added CLI commands for IAM user and policy attachment

2023-07-17 19:09 UTC, iamprakkie commented on docs/patterns/multi-account-monitoring.md
> +1. Bootstrap all 4 AWS accounts using step mentioned for **different environment for deploying CDK applications** in [Deploying Pipelines](https://aws-quickstart.github.io/cdk-eks-blueprints/pipeline
added CLI commands for bootstrapping

2023-07-17 19:19 UTC, elamaran11 approved these changes
LGTM. Nice work on improving the doc

2023-07-17 19:20 UTC, merged