Konveyor Addon Pattern
aws-samples/cdk-eks-blueprints-patterns pull request #139
Opened 2023-09-04 13:17 UTC by ariveroi

*Issue #, if available:*

*Description of changes:*

Created based on this PR: https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/91

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-05 14:00 UTC, elamaran11 requested changes
@ariveroi Thankyou for taking time to submit a PR. Im confused if its a Partner Addon or an open source addon. We have some gaps as highlighted below :
1. Is this an open source product or a Partner product. Blueprints Partner or Open Source Addon is missing in cdk-blueprints-repo. Please check our [extendability](https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#public-extensions) guide for Public/private/partner extensions. These two PRs needs to be submitted in parallel for review.
2. Do we have any license for this product if so, please share it with us.
3. If this is a partner product, do we have confirmation from partner to support ongoing manitenance of the addon, if so, please have the partner confirm in both PRs.
4. For this PR Readme update is missing for `make list` command and other spot
5. `mkdocs.yml` update is missing for the addon documentation.

2023-09-05 14:00 UTC, elamaran11 commented on docs/patterns/konveyor.md
> +<img src="./addon/src/assets/img.png"/>
Where is this image, i dont see in PR?

2023-09-05 14:00 UTC, elamaran11 commented on package.json
>      "@aws-quickstart/eks-blueprints": "1.10.1",
Make sure blueprints version is updated

2023-09-05 14:00 UTC, elamaran11 commented on package.json
>      "@aws-quickstart/eks-blueprints": "1.10.1",
Make sure blueprints version is updated

2023-09-14 07:42 UTC, ariveroi commented on docs/patterns/konveyor.md
> +<img src="./addon/src/assets/img.png"/>
fixed, added the image to the images folder

2023-09-14 07:42 UTC, ariveroi commented on package.json
>      "@aws-quickstart/eks-blueprints": "1.10.1",
updated

2023-09-14 14:01 UTC, elamaran11 requested changes
@ariveroi Thankyou for taking time to update the PR. We have some gaps as highlighted below :

- Do we have any license for this product if so, please share it with us.
- The doc is missing secret manager command to add secret to AWS environment as highlighted.
- Do we have confirmation from partner to support ongoing maintenance of the addon, if so, please have the partner confirm in both PRs.
- Make sure you pull the code from main because we had some breaking change going in yesterday

2023-09-25 16:28 UTC, cbellone commented
hello @elamaran11

This is Celestino Bellone, I am an employee of Claranet Switzerland, and I am one of the maintainers of https://github.com/claranet-ch/konveyor-eks-blueprint-addon .

As requested, this is to confirm that Claranet will support the ongoing maintenance of the Konveyor EKS Addon.

Let me know if you need anything else from our side.

Thanks,
Celestino

2023-09-25 17:04 UTC, elamaran11 commented
> hello @elamaran11
> 
> This is Celestino Bellone, I am an employee of Claranet Switzerland, and I am one of the maintainers of https://github.com/claranet-ch/konveyor-eks-blueprint-addon .
> 
> As requested, this is to confirm that Claranet will support the ongoing maintenance of the Konveyor EKS Addon.
> 
> Let me know if you need anything else from our side.
> 
> Thanks, Celestino

Thankyou @cbellone Appreciate your notes on the PR. This is enough for us to proceed with further review. We will work with @ariveroi to help him work on the comments and get this merged asap.

2023-09-29 19:42 UTC, elamaran11 requested changes
@ariveroi Minor change. If this already peer validated by Riccardo, can you ask him to comment on the PR on the peer validation

2023-09-29 19:42 UTC, elamaran11 commented on docs/patterns/konveyor.md
> +## Example configuration
This example configuration should be removed in this repo because you already have a pattern code.

2023-10-13 13:07 UTC, freschri approved these changes

2023-10-23 12:45 UTC, elamaran11 approved these changes
LGTM

2023-10-23 13:14 UTC, merged