Add karpenter windows
aws-samples/cdk-eks-blueprints-patterns pull request #140
Opened 2023-09-05 15:31 UTC by ROunofF

*Issue #, if available:*

*Description of changes:* Create a karpenter provisioner for Windows 2022

Blocked by https://github.com/aws-quickstart/cdk-eks-blueprints/pull/836

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-05 15:33 UTC, elamaran11 reviewed
LGTM. Approval blocked till next blueprints release.

2023-09-08 20:43 UTC, shapirov103 reviewed
Nice PR, great work! Please see some design/code comments, nothing major.

2023-09-08 20:43 UTC, shapirov103 commented on lib/common/windows-builder.ts
> +        id: options.genericNodeGroupTags["Name"],
We can't make this assignment here. `genericNodeGroupTags` is an optional field. Plus it is for tags specifically, so it won't be apparent to the end users that this will translate into nodegroup name. 

However, you intention of making the node group id configurable is correct. So let's just add optional fields to the windowsoptions for generic and windows node group names and if provided use those, otherwise use defaults.

2023-09-08 20:43 UTC, shapirov103 commented on lib/common/windows-builder.ts
> +        id: options.windowsNodeGroupTags["Name"],
Same comment as for the generic node group.

2023-09-13 20:34 UTC, elamaran11 commented
@ROunofF Could we move this to finish line?

2023-09-19 20:10 UTC, shapirov103 reviewed
@ROunofF please see my comment

2023-09-19 20:10 UTC, shapirov103 commented on lib/common/windows-builder.ts
> +        id: options.genericNodeGroupTags["Name"],
It will be confusing from the software design perspective to have a mandatory parameter hidden in the array of tags under a particular arbitrary name "Name". 
Explicit design with the name field is way more straightforward and eliminates hidden side effects (like the need to have tags, not empty, populated with some mandatory tags). Plus separation of concerns - tags are just not meant for it. 

So let's move forward with the explicit approach. 

At the moment we have something like `windowsNodeGroupTags` and `genericNodeGroupTags`.  these can be repurposed to be `windowsNodeGroupOptions: ManagedNodeGroup` and `genericNodeGroupOptions: ManagedNodeGroup`. These structures already have tags and ids.

I am sure some customers will want a particular instance type for each, so it makes sense to allow this flexibility if this code is to be more than just a demo.

2023-12-21 18:57 UTC, ROunofF commented
Changed to use cdk-eks-blueprint builder. Remove local builder and some cleanup.

Change to use the eks.nodeGroupOptions so we can override any parameters.

2023-12-21 19:22 UTC, elamaran11 reviewed
@ROunofF You need check comments on Blueprints repo. Also did you get a chance to fully test by packing `WindowsBuilder`

2023-12-21 19:22 UTC, elamaran11 commented on lib/windows-construct/index.ts
> +        const karpenterAddon = new blueprints.addons.KarpenterAddOn({
Why dont we move this to `windowsBuilder` ? Also you can add this enable option. Check `ObservabilityBuilder` reference?

2023-12-21 19:22 UTC, elamaran11 commented on lib/windows-construct/index.ts
>  import * as eks from "aws-cdk-lib/aws-eks";
Fix GH action

2023-12-21 19:29 UTC, ROunofF commented on lib/windows-construct/index.ts
> +        const karpenterAddon = new blueprints.addons.KarpenterAddOn({
Let me check if I can do that.

2024-03-21 00:23 UTC, elamaran11 commented
@ROunofF We had a blueprints release recently. Can you bring this PR to closure.

2024-04-02 20:58 UTC, elamaran11 reviewed
@ROunofF Nice work, a minor comment to fix the `aws-cdk` and `aws-cdk-lib` version in alignment to blueprints supported version. Did you test it to make sure everything works fine? Once you confirm i can kick in e2e. Also a minor GH Warning to add `version` to `generic-construct`

2024-04-02 20:58 UTC, elamaran11 commented on package.json
>      "aws-cdk": "2.115.0",
Please update `aws-cdk` version too.

2024-04-02 20:58 UTC, elamaran11 commented on package.json
>      "aws-cdk-lib": "2.115.0",
`aws-cdk-lib` this too

2024-04-09 20:57 UTC, elamaran11 reviewed
@ROunofF Everything looks good to me. Did you test it, does the pattern work fine for you? Once #166 is merged, you can merge from main to avoid unnecessary files in PR. Let me run e2e for Windows Pattern.

2024-04-09 20:58 UTC, elamaran11 commented
/do-e2e-tests windows deploy

2024-04-09 21:06 UTC, ROunofF commented
> @ROunofF Everything looks good to me. Did you test it, does the pattern work fine for you? Once #166 is merged, you can merge from main to avoid unnecessary files in PR. Let me run e2e for Windows Pattern.

Yes that pattern was working, had a few problem with unrelated pattern so I used the fix from the PR mentioning it

2024-04-10 20:50 UTC, shapirov103 commented
/do-e2e-tests windows deploy

2024-04-12 13:58 UTC, elamaran11 requested changes
@ROunofF Minor comment. Region hard code should be avoided in generic patterns.

2024-04-12 13:58 UTC, elamaran11 commented on lib/karpenter-construct/index.ts
> +                    { key: 'topology.kubernetes.io/zone', operator: 'NotIn', values: ['us-west-2c']},
Why are we hard coding regions in generic patterns? And `[`${region}a`,`${region}b`, `${region}c`]` seems to be removed.

2024-04-12 14:04 UTC, ROunofF commented on lib/karpenter-construct/index.ts
> +                    { key: 'topology.kubernetes.io/zone', operator: 'NotIn', values: ['us-west-2c']},
Fixed

2024-04-12 14:04 UTC, elamaran11 reviewed
LGTM. Let me run E2E.

2024-04-12 14:04 UTC, elamaran11 commented
/do-e2e-tests windows deploy

2024-04-12 16:05 UTC, elamaran11 commented
/do-e2e-tests kubeflow deploy

2024-04-12 21:05 UTC, elamaran11 commented
/do-e2e-tests kubeflow deploy

2024-04-13 00:14 UTC, elamaran11 commented
/do-e2e-test windows deploy

2024-04-13 14:03 UTC, elamaran11 commented
/do-e2e-test windows destroy

2024-04-13 15:24 UTC, elamaran11 approved these changes
LGTM, Thanks for the contribution @ROunofF

2024-04-13 15:24 UTC, merged