Added a new pattern Resilience Backup Restore using Native AWS Services
aws-samples/cdk-eks-blueprints-patterns pull request #156
Opened 2023-12-21 13:30 UTC by prabaksa

*Issue #, if available:* 

*Description of changes:* Added a new pattern Resilience Backup Restore using Native AWS Services . Added files under bin, docs and lib folders. Changed CDK Version from 2.99.1 to 2.107.0 in package.json

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-21 15:23 UTC, shapirov103 commented
@elamaran11  please review at your convenience.
@prabaksa I will update the libraries to use the latest CDK, you will need to merge that change.

2023-12-21 16:03 UTC, elamaran11 commented
> @elamaran11 please review at your convenience. @prabaksa I will update the libraries to use the latest CDK, you will need to merge that change.

Sounds good!

2023-12-21 16:13 UTC, elamaran11 commented
@prabaksa Is the PR fully ready to review. Last time we spoke, i thought you were working on Architectural changes?

2023-12-21 18:34 UTC, elamaran11 reviewed
@prabaksa AWSome work. Some high level feedback:
1. How are we simulating failure and demonstrate the same? We should simulate failure and show the restore process.
2. Are you planning to run sample workload as we discussed? We need show a workload like yelb, wordpress with some state in EBS restored
3. `package.json` should be updated with latest blueprints version, cdk and all other dependencies
4. I think you should have single documentation demonstrating the complete DR flow.
5. Also the diagram in restore process is not correct, it should DR region running the workload.
6. `destroy "*"` should destroy all stack.

2024-02-08 19:35 UTC, elamaran11 requested changes
@prabaksa Overall looks great. AWSome work. I have some minor tactical feedback please fix this and i can run it once and merge. Also please see GH actions failing due to doc links. Please fix it all and i can run and merge.

2024-02-08 19:35 UTC, elamaran11 commented on bin/resilience-br-backup-aws.ts
> +import ResilienceBRAWSConstruct from '../lib/resilience/backup_restore/backup/aws';
`ResilienceBRAWSConstruct` doesnt look like standard convention. What is `BRAWS`?

2024-02-08 19:35 UTC, elamaran11 commented on bin/resilience-br-restore-aws.ts
> +import ResilienceBRAWSConstruct from '../lib/resilience/backup_restore/restore/aws';
`ResilienceBRAWSConstruct` doesnt look like standard convention. What is `BRAWS`?

2024-02-08 19:35 UTC, elamaran11 commented on cdk.json
> +    "app": "npx ts-node dist/lib/common/default-main.js",
Lets remove `cdk.json` changes. This should go in the doc.

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/backupstack.ts
> +    //drbackupVault: { "backupVaultArn": string, backupVaultName: string, env: {"account": string , region: string}}
Why is this commented?

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/backupstack.ts
> +        //const drregion = blueprints.utils.valueFromContext(scope, "resilience-backup-restore-aws.dr.region", undefined);
Why is this commented?

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/drstack.ts
> +            //drbackupVault: { "backupVaultArn": drbackupVault.attrArn, backupVaultName: drbackupVault.attrName, env: {"account": process.env.CDK_DEFAULT_ACCOUNT! , region: drregion}}
Why is this commented?

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/index.ts
> +    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
Looks like 'id' is defined but never used. Allowed unused args must match /^_/u

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/index.ts
> +    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
'props' is defined but never used. Allowed unused args must match /^_/u

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/index.ts
> +        const kmsAlias = new kms.CfnAlias(stack, 'KMSAlias', {
'kmsAlias' is assigned a value but never used

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/backupstack.ts
> +        //const drregion = blueprints.utils.valueFromContext(scope, "resilience-backup-restore-aws.dr.region", undefined);
remove this.

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/drstack.ts
> +            //drbackupVault: { "backupVaultArn": drbackupVault.attrArn, backupVaultName: drbackupVault.attrName, env: {"account": process.env.CDK_DEFAULT_ACCOUNT! , region: drregion}}
remove

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/index.ts
> +    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
'id' is defined but never used. Allowed unused args must match /^_/u

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/index.ts
> +    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
'props' is defined but never used. Allowed unused args must match /^_/u

2024-02-08 19:35 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/index.ts
> +        const kmsAlias = new kms.CfnAlias(stack, 'KMSAlias', {
'kmsAlias'

2024-02-09 03:18 UTC, prabaksa commented on bin/resilience-br-backup-aws.ts
> +import ResilienceBRAWSConstruct from '../lib/resilience/backup_restore/backup/aws';
Backup/Restore AWS

2024-02-09 03:18 UTC, prabaksa commented on cdk.json
> +    "app": "npx ts-node dist/lib/common/default-main.js",
ok

2024-02-09 03:19 UTC, prabaksa commented on lib/resilience/backup_restore/backup/aws/backupstack.ts
> +    //drbackupVault: { "backupVaultArn": string, backupVaultName: string, env: {"account": string , region: string}}
I will remove this, It is not required anymore.

2024-02-09 03:19 UTC, prabaksa commented on lib/resilience/backup_restore/backup/aws/backupstack.ts
> +        //const drregion = blueprints.utils.valueFromContext(scope, "resilience-backup-restore-aws.dr.region", undefined);
not used in this construct, will remove this earlier since everything was on a single file i had defined all the variables in the file.

2024-02-09 13:32 UTC, elamaran11 requested changes
One more Comment. We need to Bootstrap the Argo right. We need an env and env maps to teams and we will have separate ArgoConfig. Check this example - https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/b6ad0cacde6faf75b2a8d997b1f490af466550b0/lib/multi-account-monitoring/pipeline.ts#L141

2024-02-09 13:32 UTC, elamaran11 commented on lib/resilience/backup_restore/backup/aws/index.ts
> +                bootstrapRepo: {
We dont bootstrap Argo like this. We need an env and env maps to teams and we will have separate ArgoConfig. Check this example - https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/b6ad0cacde6faf75b2a8d997b1f490af466550b0/lib/multi-account-monitoring/pipeline.ts#L141

2024-02-09 13:32 UTC, elamaran11 commented on lib/resilience/backup_restore/restore/aws/index.ts
> +                bootstrapRepo: {
We dont bootstrap Argo like this. We need an env and env maps to teams and we will have separate ArgoConfig. Check this example - https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/b6ad0cacde6faf75b2a8d997b1f490af466550b0/lib/multi-account-monitoring/pipeline.ts#L141

2024-02-12 22:33 UTC, shapirov103 requested changes
@prabaksa do you mind throwing a 30 min meeting to discuss the design here? I see a bunch of CDK stacks outside of the blueprints and also shell scripts. The objective of the meeting is to review the design and find the opps to improve customer experience.

2025-01-12 00:20 UTC, closed without merging