Multiple Cluster testing pipeline
aws-samples/cdk-eks-blueprints-patterns pull request #160
Opened 2024-02-08 01:02 UTC by Howlla

*Issue #, if available:*

*Description of changes:* Testing pipeline for Kube 1.24 to 1.27 with x86 and ARM architectures

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-09 21:34 UTC, Howlla commented
I run this with 
```
 make pattern multi-cluster-conformitron deploy multi-cluster-central-pipeline
 ```

2024-02-12 21:33 UTC, elamaran11 requested changes
@Howlla As discussed, I recommend the following:
1. A Blueprints Construct holding the cluster setup with addons
2. Using K8s version map to render versions with Construct with stages for pipeline for multiple clusters.
3. Remove Argo out of the equation. Use FluxConfig

2024-02-12 21:33 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +        const account = "810198167072";
Remove Account numbers from PR

2024-02-12 21:33 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +function createArgoAddonConfig(environment: string, repoUrl: string): blueprints.ArgoCDAddOn {
ArgoConfig should removed.

2024-02-12 21:33 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +                            .addOns(prodArgoAddonConfig)
ArgoConfig

2024-02-13 14:17 UTC, elamaran11 requested changes
@Howlla Overall looks great, I have some minor feedback. 
1. Documentation is missing
2. Reference doc to mkdocs for the pattern
3. Commented code cleanup, remove account numbers and personal owner reference
4. Think about accommodating BottleRocket as one of the cluster type
5. I recommend creating a specific Construct or reusing Observability Builder class in this as Construct which can be rendered multi times to create many clusters
6. Multi Account Observability should be part of this. You can refer to our Multi Account Mon pattern in CDK Accelerator.
7. Centralized Logging with ADOT to CW
8. Centralized tracing with ADOT to X-RAY
9. Centralized Monitoring with ADOT to AMP
10. Grafana Operator and Grafana Dashboarding for multi cluster should be a part.
11. We should bring in Hardening to Clusters using tools like Trivy, Kyverno (Mike should help you with this).

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +        .owner('Howlla')
This will have to change when you merge!

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +                    metadata: {name: "eks-cloud-secret-store"},
Is this name accurate. Can you work with Mike to see what we have in Conformance Private Repo for Conformitron?

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +                    metadata: {name: "eks-cloud-configmap-store"},
Is this name accurate. Can you work with Mike to see what we have in Conformance Private Repo for Conformitron?

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/index.ts
> +export { PipelineMultiCluster } from './pipeline';
Why do we need this file?

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +            new blueprints.addons.ExternalsSecretsAddOn(),
What about other mandatory addons like KubeProxy, CoreDNS, ALB, Cert Manager etc. I think you should add some minimal addons like Observability Builder.

2024-02-13 14:17 UTC, elamaran11 commented on lib/multi-cluster-construct/pipeline.ts
> +            new blueprints.addons.FluxCDAddOn({
I also recommend creating a separate construct if possible. Also see if you can keep the Flux Config outside like in `cdk.json` file like how we do in CDK Accelerator.

2024-02-19 11:38 UTC, Howlla commented on lib/multi-cluster-construct/pipeline.ts
> +        .owner('Howlla')
changes done

2024-02-19 11:38 UTC, Howlla commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +                    metadata: {name: "eks-cloud-secret-store"},
Mike informed me of this

2024-02-19 11:38 UTC, Howlla commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +                    metadata: {name: "eks-cloud-configmap-store"},
yes, this snippet was shared from Mike

2024-02-19 11:46 UTC, Howlla commented
Hi @elamaran11 Current status


1.     Documentation is missing - Added
2.     Reference doc to mkdocs for the pattern - Added
3.     Commented code cleanup, remove account numbers and personal owner reference  - Removed
4.     Think about accommodating BottleRocket as one of the cluster type - Added
5.     I recommend creating a specific Construct or reusing Observability Builder class in this as Construct which can be rendered multi times to create many clusters - Added
6.     Multi Account Observability should be part of this. You can refer to our Multi Account Mon pattern in CDK Accelerator. - Didnt use multi accounts
7.     Centralized Logging with ADOT to CW - oss observability added
8.     Centralized tracing with ADOT to X-RAY - oss observability added
9.     Centralized Monitoring with ADOT to AMP - oss observability added
10.     Grafana Operator and Grafana Dashboarding for multi cluster should be a part. - additional cluster added for grafana
11.     We should bring in Hardening to Clusters using tools like Trivy, Kyverno - future work

2024-02-20 21:11 UTC, elamaran11 reviewed
Bhavye. Approach looks very good and well aligned. Did this work and were you able to see metrics of all clusters in AMG console? Can you show a demo of this operating and all ISVS working on friday?

2024-02-21 01:51 UTC, elamaran11 reviewed
Doc needs some work, Please remove all ArgoCD references and write a bit about Conformitron and what we are accomplishing here!

2024-02-21 01:51 UTC, elamaran11 commented on docs/patterns/multi-cluster-conformitron.md
> +1. Application team - it defines 3 application teams that corresponds with the 3 sample applications used
We are not using ArgoCD, Please remove all ArgoCD Reference.

2024-02-21 01:51 UTC, elamaran11 commented on docs/patterns/multi-cluster-conformitron.md
> +1. `github-ssh-key` - must contain GitHub SSH private key as a JSON structure containing fields `sshPrivateKey` and `url`. This will be used by ArgoCD addon to authenticate against ay GitHub reposito
Why is this required?

2024-06-08 01:42 UTC, Howlla commented
New PR Created Here https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/176

2024-06-08 01:42 UTC, closed without merging