Adding new pattern for Crossplane Argocd GitOps
aws-samples/cdk-eks-blueprints-patterns pull request #173
Opened 2024-05-15 11:01 UTC by ajpaws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-15 12:21 UTC, elamaran11 requested changes
@ajpaws Thankyou for working on this and quick PR. There are few alignments to the approach we have to make :
1. First the arrangment is not aligning to the theme of the repo. You should have one bin `ts` file for this pattern which invokes the class in the lib file to run the pattern. Please check other patterns like SecureIngress Pattern which we worked for another blog.
2. I understand you most of the code i shared from my partner work but we cant reuse it as is, we need to refactor it work with patterns repo. We done need this file `aws-addon-clusters-stack.ts` for instance. Plus we need one pipeline which deploys management cluster and all child cluster and those pipeline code should be in lib folder like multi account monitoring pattern.
3. So basically most of the work you have in bin folder should move to lib folder refactored.
4. See if you have any opportunities to minimize the number of custom addons. 
Overall great progress, we have some work to do. Lets connect if you have questions.

2024-06-11 04:28 UTC, elamaran11 reviewed
@ajpaws Awesome work. Love the idea of adding Pod Identity Addon via `ClusterAuth` We are very near to finish line. One minor feedback that i mentioned on bin file.  Also lets add the architecture diagram of the blog optionally to make this complete.

2024-06-11 04:28 UTC, elamaran11 commented on bin/crossplane-argocd-gitops.ts
> +const account = process.env.CDK_DEFAULT_ACCOUNT ?? "";
Lets move all of line 13 - 42 to lib stack as per our standard of the repo. We keep bin file just for separation of concerns of different patterns.

2024-06-24 17:58 UTC, shapirov103 reviewed
@ajpaws  great work, a lot of effort. I went through the first round of review and let's fix the issues, I also posted a couple of questions. I will review again after you are done, and we will validate it  as well. I realize there is a dependency on the workloads repo PR.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/common/construct-utils.ts
> +import { utils } from "@aws-quickstart/eks-blueprints";
Was it a conscious decision to duplicate this file from `lib/common/construct-utils.ts` and move it under your pattern directory? Let's remove it.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/crossplane-k8s-provider-addon.ts
> +                package: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0",
do we have to hardcode the version here? If it is changing frequently, the best approach is to pass it as an option to the addon.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +import 'source-map-support/register';
@elamaran11 is there a rationale why this addon is not in the blueprints repo? We have upbound addon there, it may be confusing to the customers how to reconcile this with the one in the blueprints repo. I assume we should deprecate or just replace the upbound addon in the blueprints.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/management-cluster-builder.ts
> +            tags: {"scope": "addon"},
what is reason for these tag?

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            owner :'jalawala',
I assume this should change after the workloads PR is merged? Let's apply this change after the workloads merge is complete.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +                    new GenericClusterProvider( {
let's create a simple function `createClusterProvider(instanceClass: InstanceClass)` and use it on line 100 and line 115 
If you see fit we can pass more args to this function.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +    async prevalidateSecrets(secretName: string, region: string) {
Looks like a duplication of a common function, let's remove it.

2024-06-24 17:58 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            .resourceProvider('eks-connector-role',  new LookupRoleProvider('eks-connector-role'))
where is this role created?

2024-06-24 17:58 UTC, shapirov103 commented on docs/patterns/crosplane-argocd-gitops.md
> +# GitOps based Multi Cluster Addon and Apps Managament using Crossplane and ArgoCD
minor: 
1. rename the file to crossplane-argocd-gitops (now states crosplane)
2. Managament = Management
3. Multi Cluster = Mulit-cluster

2024-06-24 17:58 UTC, shapirov103 commented on docs/patterns/crosplane-argocd-gitops.md
> +The objective of this pattern is to provide GitOps based lifecycle management of Amazon EKS Addons, Kubernetes Applications and Helm charts across various workload clusters using ArgoCD and Crossplan
Let's run this through spell check as I see minor issues here and there throughout. Also please feel free to use cedric or other productivity tools to improve readability.

2024-06-24 18:19 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +import 'source-map-support/register';
@shapirov103 The upbound addon in Blueprints is EKS Addon and they are no longer supporting it. I asked the team but no response so the Ubound addon on the bluepeints should be depracated or this should be updated there. I think for now lets depracate upbound addon for upcoming release. I will plan to work to move this later to blueprints.

2024-06-25 00:40 UTC, ajpaws commented on lib/crossplane-argocd-gitops/common/construct-utils.ts
> +import { utils } from "@aws-quickstart/eks-blueprints";
done

2024-06-25 01:18 UTC, ajpaws commented on lib/crossplane-argocd-gitops/custom-addons/crossplane-k8s-provider-addon.ts
> +                package: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0",
done

2024-06-25 01:21 UTC, ajpaws commented on lib/crossplane-argocd-gitops/management-cluster-builder.ts
> +            tags: {"scope": "addon"},
removed since we do not seem to use them

2024-06-25 01:30 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            owner :'jalawala',
changed. this one is for building pipeline and needs to point to this repo

2024-06-25 01:34 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +                    new GenericClusterProvider( {
leaving it as it is for now to leverage built-in functions  such as GenericClusterProvider() as much as possible and avoid custom functions to keep it simple

2024-06-25 01:44 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +    async prevalidateSecrets(secretName: string, region: string) {
done

2024-06-25 02:11 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            .resourceProvider('eks-connector-role',  new LookupRoleProvider('eks-connector-role'))
looks like this needs to be created as part of pre-requisites. here we seem to look for an existing role. @elamaran11 pls confirm once

2024-06-25 02:15 UTC, ajpaws commented on docs/patterns/crosplane-argocd-gitops.md
> +# GitOps based Multi Cluster Addon and Apps Managament using Crossplane and ArgoCD
done

2024-06-25 02:32 UTC, ajpaws commented on docs/patterns/crosplane-argocd-gitops.md
> +The objective of this pattern is to provide GitOps based lifecycle management of Amazon EKS Addons, Kubernetes Applications and Helm charts across various workload clusters using ArgoCD and Crossplan
made some edits. feel free to change as needed

2024-06-25 04:14 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +                        "Resource": `arn:aws:iam::${cluster.stack.account}:role/eks-connector-role`
@shapirov103 @ajpaws Here is where the `eks-connector-role` is created. in CXP Addon.

2024-06-25 04:15 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            .resourceProvider('eks-connector-role',  new LookupRoleProvider('eks-connector-role'))
Check [this](https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/173#discussion_r1651963156) comment. it is created in CrossPlane Addon.

2024-06-26 14:14 UTC, elamaran11 reviewed
@ajpaws Fix this for GH Action to run.

2024-06-26 14:14 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +const account = process.env.CDK_DEFAULT_ACCOUNT;
@ajpaws This line should have `!` at the end.

2024-07-13 10:52 UTC, elamaran11 commented
@shapirov103 Could you please check again and let me know if this is good to merge.

2024-07-16 18:41 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +                        "Resource": `arn:aws:iam::${cluster.stack.account}:role/eks-connector-role`
@elamaran11 it is a reference to the role, not creation.

2024-07-16 18:41 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            .resourceProvider('eks-connector-role',  new LookupRoleProvider('eks-connector-role'))
I replied to your comment. I don't see the role creation, that means that it should either be created somewhere in the stacks or become part of the prerequisites which is less ideal.

2024-07-16 19:12 UTC, shapirov103 reviewed
@ajpaws please see my additional comments. Thank you for addressing my previous comments, I see some were deferred and that is ok. 

I left a bunch of minor comments, but there a few important. Happy to discuss if needed. I will focus on the workloads PR. 

@elamaran11 FYI ^^

2024-07-16 19:12 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +                    new GenericClusterProvider( {
deferred, i can refactor later

2024-07-16 19:12 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/crossplane-k8s-provider-addon.ts
> +        const role_binding1 = {
why are all the variables here postfixed with "1"? why not just role_binding?

Also please use camel case for name as opposed to python naming, we use https://google.github.io/styleguide/tsguide.html. 

So roleBinding vs role_binding. Applies elsewhere.

2024-07-16 19:12 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/mgmt-role-teams.ts
> +export class ProviderMgmtRoleTeam extends PlatformTeam {
Let's clarify the purpose of that team in the pattern doc and comment. What are we achieving with it?

2024-07-16 19:12 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +import 'source-map-support/register';
It is already in 1.15, let's replace it here, - too much code as it stands for the pattern.

2024-07-16 19:12 UTC, shapirov103 commented on lib/crossplane-argocd-gitops/multi-cluster-options.ts
> +export const K8S_VERSIONS_PROD :  KubernetesVersion[] = [KubernetesVersion.V1_25, KubernetesVersion.V1_26,
why not shift it to 27, 28, 29?

2024-08-30 04:31 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-options.ts
> +export const K8S_VERSIONS_PROD :  KubernetesVersion[] = [KubernetesVersion.V1_25, KubernetesVersion.V1_26,
done

2024-08-30 04:31 UTC, ajpaws commented on lib/crossplane-argocd-gitops/custom-addons/mgmt-role-teams.ts
> +export class ProviderMgmtRoleTeam extends PlatformTeam {
removed it as it is not needed anymore.

2024-08-30 04:31 UTC, ajpaws commented on lib/crossplane-argocd-gitops/custom-addons/crossplane-k8s-provider-addon.ts
> +        const role_binding1 = {
cleaned it

2024-08-30 04:32 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +Both of the Workload EKS Clusters i.e. `amd-1-29-blueprint` and `arm-1-29-blueprint` are added a platform team IAM Role `eks-connector-role` with `system:masters` access using the AWS Auth Config Map
cleaned this. removed team completely and updated doc

2024-08-30 04:33 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +### Update the Trust policy for the Upbound AWS EKS Provider IAM Role.
done. created a dedicated role for eks provider pod

2024-08-30 04:33 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +* AWS CodePipeline which deploy the Management and Workload Clusters
done

2024-08-30 04:33 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +This helps platform teams to simplify the process of deploying Addos and Apps from a central Management Cluster. In this Solution, we use CDK to deploy AWS CodePipeline which monitors this platform r
done

2024-08-30 04:33 UTC, ajpaws commented
> @shapirov103 Could you please check again and let me know if this is good to merge.

tested end to end once. good to merge

2024-08-30 04:34 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +const account = process.env.CDK_DEFAULT_ACCOUNT;
done

2024-08-30 04:42 UTC, ajpaws commented
> @shapirov103 Could you please check again and let me know if this is good to merge.



> @ajpaws Thankyou for working on this and quick PR. There are few alignments to the approach we have to make :
> 
> 1. First the arrangment is not aligning to the theme of the repo. You should have one bin `ts` file for this pattern which invokes the class in the lib file to run the pattern. Please check other patterns like SecureIngress Pattern which we worked for another blog.
> 2. I understand you most of the code i shared from my partner work but we cant reuse it as is, we need to refactor it work with patterns repo. We done need this file `aws-addon-clusters-stack.ts` for instance. Plus we need one pipeline which deploys management cluster and all child cluster and those pipeline code should be in lib folder like multi account monitoring pattern.
> 3. So basically most of the work you have in bin folder should move to lib folder refactored.
> 4. See if you have any opportunities to minimize the number of custom addons.
> 5. Also fix all GH Warnings and errors.
>    Overall great progress, we have some work to do. Lets connect if you have questions.

done. made all changes

2024-08-30 04:42 UTC, ajpaws commented
> @ajpaws Thankyou for working on this and quick PR. There are few alignments to the approach we have to make :
> 
> 1. First the arrangment is not aligning to the theme of the repo. You should have one bin `ts` file for this pattern which invokes the class in the lib file to run the pattern. Please check other patterns like SecureIngress Pattern which we worked for another blog.
> 2. I understand you most of the code i shared from my partner work but we cant reuse it as is, we need to refactor it work with patterns repo. We done need this file `aws-addon-clusters-stack.ts` for instance. Plus we need one pipeline which deploys management cluster and all child cluster and those pipeline code should be in lib folder like multi account monitoring pattern.
> 3. So basically most of the work you have in bin folder should move to lib folder refactored.
> 4. See if you have any opportunities to minimize the number of custom addons.
> 5. Also fix all GH Warnings and errors.
>    Overall great progress, we have some work to do. Lets connect if you have questions.

done

2024-08-30 14:50 UTC, shapirov103 reviewed
Overall looks good to me, pending resolution of feedback and functional verification by @elamaran11

2024-09-04 05:44 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +make pattern aws-addon-clusters deploy
fixed

2024-09-04 06:08 UTC, ajpaws commented
> @ajpaws Please pull from main to get past the Markdown error,.

done

2024-09-04 12:14 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +import 'source-map-support/register';
@ajpaws This comment?

2024-09-04 12:23 UTC, ajpaws commented on lib/crossplane-argocd-gitops/custom-addons/upbound-crossplane-addon.ts
> +import 'source-map-support/register';
I believe we are deprecating upbound addon in Blueprints is EKS Addon so no changed made on this. I would recommend go ahead with this for now since anyway we have code for all other upbound addons at one place in custom addons folder.

2024-09-10 14:01 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +export AWS_REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')
This is not accurate for mac based deployments. May work from Cloud9. I think you should ask the readers to hardcode ther egion.

2024-09-10 14:14 UTC, elamaran11 commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            secretName : props.gitHubSecret ?? 'cdk_blueprints_gitops_github_secret',
Secret you are creating is export CDK_REPO_AWS_SECRET_NAME="cdk_blueprints_github_secret" but the code has cdk_blueprints_gitops_github_secret

2024-09-10 16:25 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +export AWS_REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')
done

2024-09-10 16:26 UTC, ajpaws commented on lib/crossplane-argocd-gitops/multi-cluster-pipeline.ts
> +            secretName : props.gitHubSecret ?? 'cdk_blueprints_gitops_github_secret',
done

2024-09-10 20:52 UTC, elamaran11 commented
@ajpaws Cleanup Instructions are missing

2024-09-10 21:31 UTC, elamaran11 requested changes

2024-09-10 21:31 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +aws eks update-kubeconfig --name mgmt-cluster --region us-west-2 --role-arn arn:aws:iam::ACCOUNT_ID:role/mgmt-cluster-stage-mgmt-c-managementclusterAccessRo-XYSC5PKL8WnA
This is not correct

2024-09-10 21:46 UTC, elamaran11 requested changes

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +aws eks update-kubeconfig --name workload-amd-1-29-blueprint --region us-west-2 --role-arn arn:aws:iam::ACCOUNT_ID:role/eks-workload-connector-role
This is in correct too. You should basically have a command to query outputs from stack and grab or from console.

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +aws eks update-kubeconfig --name workload-arm-1-29-blueprint --region us-west-2 --role-arn arn:aws:iam::$ACCOUNT_ID:role/eks-workload-connector-role
This is in correct too. You should basically have a command to query outputs from stack and grab or from console.

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +Added new context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/workload-amd-1-29-blueprint to /Users/jalawala/.kube/config
Output can be removed.

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +Added new context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/workload-arm-1-29-blueprint to /Users/jalawala/.kube/config
Output can be removed.

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +Updated context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/mgmt-cluster in /Users/<user_name>/.kube/config
Output can be removed.

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +### Install the ArgoCD ALI
ALI?

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl --context $MANAGEMENT_CLUSTER_CONTEXT  -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
I dont see this secret, so i cant get to Argo Server. See what is missing

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl --context $MANAGEMENT_CLUSTER_CONTEXT  -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
❯ kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
─╯
Error from server (NotFound): secrets "argocd-initial-admin-secret" not found

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +argocd cluster add $MANAGEMENT_CLUSTER_CONTEXT
Fails
``` argocd cluster add arn:aws:eks:us-west-2:940019131157:cluster/mgmt-cluster
─╯
WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `arn:aws:eks:us-west-2:940019131157:cluster/mgmt-cluster` with full cluster level privileges. Do you want to continue [y/N]? y
INFO[0003] ServiceAccount "argocd-manager" created in namespace "kube-system"
INFO[0003] ClusterRole "argocd-manager-role" created
INFO[0003] ClusterRoleBinding "argocd-manager-role-binding" created
INFO[0009] Created bearer token secret for ServiceAccount "argocd-manager"
FATA[0009] Argo CD server address unspecified```

2024-09-10 21:46 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +argocd cluster add $MANAGEMENT_CLUSTER_CONTEXT
When i describe the pod. i see secret failures. Though i have `github-token` in same region.

```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    43m                default-scheduler  Successfully assigned argocd/blueprints-addon-argocd-server-666866878b-92qgh to ip-10-0-189-12.us-west-2.compute.internal
  Warning  FailedMount  6s (x29 over 43m)  kubelet            MountVolume.SetUp failed for volume "blueprints-secret-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod argocd/blueprints-addon-argocd-server-666866878b-92qgh, err: rpc error: code = Unknown desc = Failed to fetch secret from all regions: github-token
```

2024-09-11 12:17 UTC, elamaran11 requested changes

2024-09-11 12:17 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl  --context $MANAGEMENT_CLUSTER_CONTEXT get add-ons.eks.aws.upbound.io
This command should be `kubectl  --context $MANAGEMENT_CLUSTER_CONTEXT get addons.eks.aws.upbound.io`

2024-09-16 15:38 UTC, elamaran11 reviewed
@ajpaws I got everything functionall working now. The fix on INT for Account number did the trick. I see a plenty of issues with the ReadMe doc, we can merge this.

2024-09-16 15:38 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +aws secretsmanager create-secret --region $AWS_REGION \
This is not required any more

2024-09-16 22:50 UTC, ajpaws commented
> @ajpaws Cleanup Instructions are missing
done

2024-09-17 00:33 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +aws eks update-kubeconfig --name workload-amd-1-29-blueprint --region us-west-2 --role-arn arn:aws:iam::ACCOUNT_ID:role/eks-workload-connector-role
since IAM role is already known, no need to take o/p from cfn stack. we can construct the command

2024-09-17 00:34 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +aws eks update-kubeconfig --name workload-arm-1-29-blueprint --region us-west-2 --role-arn arn:aws:iam::$ACCOUNT_ID:role/eks-workload-connector-role
since IAM role is already known, no need to take o/p from cfn stack. we can construct the command

2024-09-17 00:35 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +Added new context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/workload-arm-1-29-blueprint to /Users/jalawala/.kube/config
done

2024-09-17 00:35 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +Added new context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/workload-amd-1-29-blueprint to /Users/jalawala/.kube/config
done

2024-09-17 00:36 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +Updated context arn:aws:eks:us-west-2:ACCOUNT_ID:cluster/mgmt-cluster in /Users/<user_name>/.kube/config
done

2024-09-17 04:09 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +### Install the ArgoCD ALI
fixed

2024-09-17 04:10 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl --context $MANAGEMENT_CLUSTER_CONTEXT  -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
it works once management cluster is deployed successfully

2024-09-17 04:13 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +argocd cluster add $MANAGEMENT_CLUSTER_CONTEXT
these are fixed now as we are using public repos

2024-09-17 04:14 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl  --context $MANAGEMENT_CLUSTER_CONTEXT get add-ons.eks.aws.upbound.io
fixed

2024-09-17 04:15 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +aws secretsmanager create-secret --region $AWS_REGION \
removed

2024-09-17 13:41 UTC, elamaran11 reviewed
@ajpaws One comment is still not addressed.
Also cleanup instructions are missing. Please fix those two before we can merge this.

2024-09-17 13:41 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +kubectl  --context $MANAGEMENT_CLUSTER_CONTEXT get add-ons.eks.aws.upbound.io
This is not fixed. The correct command is `kubectl get addons.eks.aws.upbound.io

2024-09-17 13:45 UTC, elamaran11 reviewed
Cleanup is incomplete.

2024-09-17 13:45 UTC, elamaran11 commented on docs/patterns/crossplane-argocd-gitops.md
> +make pattern crossplane-argocd-gitops destroy
This alone does not cleanup all the child and nested stacks. Please add instructions to ask the reader to clean up all stacks manually in CF Console or try to run a CLI command which ever works.

2024-09-17 19:26 UTC, ajpaws commented on docs/patterns/crossplane-argocd-gitops.md
> +make pattern crossplane-argocd-gitops destroy
done

2024-09-17 19:26 UTC, ajpaws commented
> Cleanup is incomplete.

fixed now

2024-09-17 19:27 UTC, ajpaws commented
> @ajpaws One comment is still not addressed. Also cleanup instructions are missing. Please fix those two before we can merge this.

done

2024-09-17 20:09 UTC, elamaran11 approved these changes
Looks Good. Great work @ajpaws Thankyou for working thoughout the proces of this development and review with us.

2024-09-17 20:09 UTC, merged