Conformitron with cost optimizations
aws-samples/cdk-eks-blueprints-patterns pull request #176
Opened 2024-06-08 01:41 UTC by Howlla

*Issue #, if available:*

*Description of changes:* Code for conformitron mult-cluster deployment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-10 12:29 UTC, elamaran11 requested changes
@Howlla Great work, almost near to finish line. Have some feedback.
1. Documentation should be improved for completeness. Overview should be added, delete instructions, screenshots of working environment etc etc to be added.
2. Lets not have separate instructions for Cost Optimization documentation. Have this in single document. Think about someone want to replicate the entire setup using your documentation. Lets have complete setup instructions.
3. `cdk.json` should not have sensitive info.

Appreciate if you can fix this, once done, can review again.

2024-06-10 12:29 UTC, elamaran11 commented on cdk.json
> +        "endpoint":"https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-b08fda60-7e79-450c-972d-262ebac98c3e/",
Please remove this hard code values from your `cdk.json` file. We should populate it via context file via env variables which should be documented in your doc like backstage pattern document.

2024-06-10 12:29 UTC, elamaran11 commented on cdk.json
> +        "endpoint":"https://g-76edcf29d5.grafana-workspace.us-west-2.amazonaws.com"
Likewise this should also be removed

2024-06-10 12:29 UTC, elamaran11 commented on docs/patterns/multi-cluster-conformitron.md
> +
Lets start with a little bit of background. You can talk about what is conformitron, what is the need for the same, what are we accomplishing etc etc. YOu can also link our conformitron blog.

2024-06-10 12:29 UTC, elamaran11 commented on docs/patterns/multi-cluster-conformitron.md
> +1. Configure the clusters with different architectures (x86 and arm) and different Kuberentes versions and use fluxCD pipeline to deploy all the available [EKS Anywhere Addons](https://github.com/aws
And Bottlerocket.

2024-06-10 12:29 UTC, elamaran11 commented on docs/patterns/multi-cluster-conformitron.md
> +Now you can go to [AWS CodePipeline console](https://eu-west-1.console.aws.amazon.com/codesuite/codepipeline/pipelines), and see how it was automatically created to deploy multiple Amazon EKS cluster
What about deleting instructions, screenshots of working environment and documentation showing how to run the optimization SSM doc setup.

2024-06-10 12:29 UTC, elamaran11 commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +# SSM Cost Optimizations for conformitron clusters
Could we remove this and this to main documentation of this pattern. lets not have two disconnected docs.

2024-06-10 12:29 UTC, elamaran11 commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +On weekdays 5 AM PST clusters are scaled to 1 -> CRON EXPRESSION:  0 05 ? * MON-FRI *
Lets also show CLI based instructions on how to set it up

2024-06-10 12:29 UTC, elamaran11 commented on lib/multi-cluster-construct/CostOptimizationSSM/ScaleUpEKStoOne.YAML
> +schemaVersion: '0.3'
Could we use some env var variables to populate cluster names etc etc so its not direct hard code to the yaml. Also why is the yaml file `YAML` format?

2024-06-28 11:33 UTC, elamaran11 commented
@Howlla Could you please bring this PR to closure. Its long pending.

2024-07-01 14:34 UTC, shapirov103 reviewed
@Howlla great work and much needed pattern. Please see some comments I left. It would be nice to test it out with 1.15.0 blueprints that we released last week.

2024-07-01 14:34 UTC, shapirov103 commented on docs/patterns/multi-cluster-conformitron.md
> +# Multi Cluster Conformitron Testing
Let's call it `Multi-cluster pattern with observability cost optimizations and metrics aggregation`. Customers won't understand Conformitron but we can call it out in the intro.

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +# SSM Cost Optimizations for conformitron clusters
+1

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +# SSM Cost Optimizations for conformitron clusters
Please remove the CostOptimizationSSM folder from lib

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +export class EksAnywhereSecretsAddon implements blueprints.ClusterAddOn {
Let's rename this to something that is more semantically correct: Looks like it is an addon that sets up secret store for secret manager and paramstore. Let's call `ClusterSecretStoreAddon`.

Applies to the addon name and file name

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/grafana-monitor-builder.ts
> +        const account = contextAccount! || process.env.COA_ACCOUNT_ID! || process.env.CDK_DEFAULT_ACCOUNT!;
What is this variable `COA_ACCOUNT_ID`? This maybe confusing to the end user of the pattern. Let's rename it to be something less confusing and document in the pattern doc.

Applies elsewhere.

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/grafana-monitor-builder.ts
> +                    __dirname + '/../common/resources/amp-config/alerting-rules.yml',
These config rules seem to be specific to the pattern, we could move them under multi-cluster-construct/resources. Let's discuss if needed.

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/grafana-operator-secret-addon.ts
> +                                remoteRef: {
"/cdk-accelerator/grafana-api-key" - how will the customers know to set it up?  Also do we need to call out cdk-accelerator here?

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/multi-cluster-builder.ts
> +                new blueprints.addons.FluxCDAddOn({
Let's call it in the docs that by default it sets up Flux CD with these GitHib repos, but that is where customers can use the GitOps tooling of their choice, as well as repos.

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/pipeline.ts
> +    getClusterProps() {
why do we need this method? It seems easier to just declare a const at the top like:

```ts
const defaultClusterProps : blueprints.MngClusterProviderProps = {
            maxSize : 2,
            minSize : 1,
            desiredSize: 1,
            diskSize: 100
        };
```

And use it where needed.

2024-07-01 14:34 UTC, shapirov103 commented on lib/multi-cluster-construct/pipeline.ts
> +            const blueprintBuilderX86 = new MultiClusterBuilderConstruct().create(scope, accountID, region);
style: let's componentize a bit more. I suggest a method  `buildClusterProps(instanceTypes, amiType)` and call it for x86 and arm. That will reduce this method size and make it more readable.

2024-07-09 09:10 UTC, Howlla commented on cdk.json
> +        "endpoint":"https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-b08fda60-7e79-450c-972d-262ebac98c3e/",
removed from cdk.json and captured it via env variables instead

2024-07-09 09:10 UTC, Howlla commented on cdk.json
> +        "endpoint":"https://g-76edcf29d5.grafana-workspace.us-west-2.amazonaws.com"
removed

2024-07-09 09:11 UTC, Howlla commented on docs/patterns/multi-cluster-conformitron.md
> +
Please give more feedback around the doc @shapirov103 @elamaran11  and I will make it work

2024-07-09 09:11 UTC, Howlla commented on docs/patterns/multi-cluster-conformitron.md
> +1. Configure the clusters with different architectures (x86 and arm) and different Kuberentes versions and use fluxCD pipeline to deploy all the available [EKS Anywhere Addons](https://github.com/aws
mentioned

2024-07-09 09:11 UTC, Howlla commented on docs/patterns/multi-cluster-conformitron.md
> +Now you can go to [AWS CodePipeline console](https://eu-west-1.console.aws.amazon.com/codesuite/codepipeline/pipelines), and see how it was automatically created to deploy multiple Amazon EKS cluster
Pending still

2024-07-09 09:11 UTC, Howlla commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +# SSM Cost Optimizations for conformitron clusters
Done

2024-07-09 09:11 UTC, Howlla commented on lib/multi-cluster-construct/CostOptimizationSSM/ScaleUpEKStoOne.YAML
> +schemaVersion: '0.3'
Pending still

2024-07-09 09:12 UTC, Howlla commented on docs/patterns/multi-cluster-conformitron.md
> +# Multi Cluster Conformitron Testing
renamed, open to more feedback on doc

2024-07-09 09:12 UTC, Howlla commented on lib/multi-cluster-construct/CostOptimizationSSM/README.md
> +# SSM Cost Optimizations for conformitron clusters
i have moved it to a multi-cluster-construct/resources folder instead

2024-07-09 09:12 UTC, Howlla commented on lib/multi-cluster-construct/eksa-secret-stores.ts
> +export class EksAnywhereSecretsAddon implements blueprints.ClusterAddOn {
Done

2024-07-09 09:12 UTC, Howlla commented on lib/multi-cluster-construct/grafana-monitor-builder.ts
> +        const account = contextAccount! || process.env.COA_ACCOUNT_ID! || process.env.CDK_DEFAULT_ACCOUNT!;
Fixed this variable name to ACCOUNT_ID

2024-07-09 09:13 UTC, Howlla commented on lib/multi-cluster-construct/grafana-monitor-builder.ts
> +                    __dirname + '/../common/resources/amp-config/alerting-rules.yml',
i have moved it to a multi-cluster-construct/resources folder instead

2024-07-09 09:13 UTC, Howlla commented on lib/multi-cluster-construct/grafana-operator-secret-addon.ts
> +                                remoteRef: {
called out in documentation now

2024-07-09 09:13 UTC, Howlla commented on lib/multi-cluster-construct/multi-cluster-builder.ts
> +                new blueprints.addons.FluxCDAddOn({
Mentioned in doc

2024-07-09 09:13 UTC, Howlla commented on lib/multi-cluster-construct/pipeline.ts
> +    getClusterProps() {
refactored

2024-07-09 09:13 UTC, Howlla commented on lib/multi-cluster-construct/pipeline.ts
> +            const blueprintBuilderX86 = new MultiClusterBuilderConstruct().create(scope, accountID, region);
refactored to use buildClusterProps function instead

2024-07-09 09:13 UTC, Howlla commented
Pending architecture diagram still.

2024-07-12 13:42 UTC, elamaran11 reviewed
Overall, everything now LGTM. @shapirov103 Please share if all your comments are fixed and let me know. I can check once again and do merge.

2024-07-30 17:24 UTC, shapirov103 commented on docs/patterns/multi-cluster-conformitron.md
> +Now you can go to [AWS CodePipeline console](https://eu-west-1.console.aws.amazon.com/codesuite/codepipeline/pipelines), and see how it was automatically created to deploy multiple Amazon EKS cluster
let's resolve this

2024-07-30 17:28 UTC, shapirov103 approved these changes
There are some minor things to improve on the doc side, like making sure you use dots at the end of the sentences, and proper casing, some spelling errors like seperate should be separate, vpc should be VPC, and such. I am willing to defer these, there is always space to improve. Please check some pending comments from Ela, like instructions to delete, which may cause some issue with ArgoCD resource being orphaned. We should be explicit about it, if there is some manual effort and gotchas, we can call them out.

2024-08-01 09:11 UTC, elamaran11 approved these changes
LGTM. @Howlla This is bar raising work, im good to merge this. Hope you can support the pattern in continuous basis for ongoing issues with Conformitron.

2024-08-01 09:12 UTC, merged