changes to add paralus addon to eks blueprint
aws-samples/cdk-eks-blueprints-patterns pull request #63
Opened 2023-03-02 12:29 UTC by niravparikh05

*Issue #, if available:*

https://github.com/aws-quickstart/cdk-eks-blueprints/issues/580

*Description of changes:*

Creates a sample eks blueprint for paralus addon

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-06 07:27 UTC, niravparikh05 commented
@parkand1 Lately I am running into below issue while running any cdk commands, even in main branch. Any idea on what's causing this and how do I fix it ?

Node Version: v16.19.1
npm version: 8.19.3
cdk version: 2.65.0

/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/sync-rpc/lib/index.js:165
    const error = new Error(msg.v.message);
                  ^
Error: read ECONNRESET
    at extractValue (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/sync-rpc/lib/index.js:165:19)
    at /home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/sync-rpc/lib/index.js:175:12
    at request (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/sync-request/lib/index.js:28:15)
    at loadExternalYaml (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/utils/yaml-utils.ts:46:22)
    at CsiDriverProviderAws.deploy (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/addons/secrets-store/csi-driver-provider-aws.ts:54:61)
    at SecretsStoreAddOn.deploy (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/addons/secrets-store/index.ts:66:53)
    at new EksBlueprint (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:263:34)
    at new MultiTeamConstruct (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/lib/multi-team-construct/index.ts:42:9)
    at Object.<anonymous> (/home/infracloud/development/vscode-workspace/aws-samples/cdk-eks-blueprints-patterns/bin/main.ts:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14) {
  code: 'ECONNRESET'
}

2023-03-14 04:17 UTC, parkand1 commented
@niravparikh05 I just tried a new deploy from the patterns repo and it is also working on my end

```bash
blueprints-addon-paralus-contour-contour-6bd75d995f-zrf9n   1/1     Running   0             64s
blueprints-addon-paralus-contour-envoy-dj5n8                2/2     Running   0             64s
blueprints-addon-paralus-fluent-bit-w7tnf                   1/1     Running   2 (48s ago)   64s
blueprints-addon-paralus-kratos-7cc678d95b-g2l9d            2/2     Running   0             64s
blueprints-addon-paralus-kratos-courier-0                   2/2     Running   0             63s
blueprints-addon-paralus-postgresql-0                       1/1     Running   0             63s
dashboard-79f8d5d6d-8lt7b                                   1/1     Running   0             64s
paralus-856ccbf875-5pn7s                                    2/2     Running   0             64s
prompt-7677588bcc-vjqhh                                     2/2     Running   0             64s
relay-server-6cb9f6cf86-d5jw9                               2/2     Running   1 (23s ago)   63s
```

The only thing I'd like to add is an example of a sample use-case in the documentation and from there I am good to merge!

2023-03-20 11:51 UTC, niravparikh05 commented
thanks @parkand1 I have added some information around a sample use-case with reference to a detailed blog around it.

2023-03-27 05:21 UTC, niravparikh05 commented
@parkand1 just following up to check if you got a chance to review the documentation changes ?

2023-03-30 01:17 UTC, parkand1 requested changes

2023-03-30 01:17 UTC, parkand1 commented on lib/paralus-construct/index.ts
> +                       "fqdn.domain": "paralus.local"
Can we update this based on our conversation today?

```bash
                    values: {
                        "fqdn": {
                         "domain": "your.domain",
                         "hostname": "console-ic-oss",
                         "coreConnectorSubdomain": "*.core-connector.ic-oss",
                         "userSubdomain": "*.user.ic-oss"
                        }
```

2023-03-31 18:26 UTC, parkand1 requested changes
Added a couple more comments

2023-04-03 09:11 UTC, niravparikh05 commented on docs/patterns/paralus.md
> +
Added a learn more link to paralus website.

2023-04-03 09:11 UTC, niravparikh05 commented on docs/patterns/paralus.md
> +- Deploys supporting add-ons:  AwsLoadBalancerController, VpcCni, KubeProxy, EbsCsiDriverAddOn
Added a note on the add-on dependencies

2023-04-03 09:14 UTC, niravparikh05 commented on docs/patterns/paralus.md
> +prompt-54d45cff79-h9x95                                    2/2     Running
probably paralus pod took a tad bit longer due to its dependencies on kratos, postgres etc., prompt attempts to verify dependent paralus services and restarts if paralus is not ready yet. 

similar behaviour is seen for relay, however it should be in running once paralus is up.

2023-04-03 09:15 UTC, niravparikh05 commented on docs/patterns/paralus.md
> +blueprints-addon-paralus-contour-contour-7857f4cd9-kqhgp   1/1     Running
added a link detailing all the various components used in paralus.

2023-04-03 09:15 UTC, niravparikh05 commented on lib/paralus-construct/index.ts
> +                       "fqdn.domain": "paralus.local"
updated accordingly.

2023-04-03 09:16 UTC, niravparikh05 commented
@parkand1 addressed all the comments and updated the pr. kindly have a look at your convenience.

2023-04-11 10:36 UTC, niravparikh05 commented
@parkand1 just following up to check if you got a chance to review the changes ?

2023-04-25 08:59 UTC, niravparikh05 commented
@parkand1 following up on this, did you get a chance to try this out ? Looking to take this forward.

2023-05-03 20:12 UTC, parkand1 approved these changes
LGTM

2023-05-04 14:41 UTC, merged