Refactored the securityhub pattern, and moved it under security.
aws-samples/cdk-eks-blueprints-patterns pull request #84
Opened 2023-05-18 22:07 UTC by sbollers

*Issue #, if available:*

*Description of changes:*
Replaced the inital code implemented with the CDK securityhub L2 construct. Moved to all pattern files to the lib/security directory. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-19 19:09 UTC, shapirov103 commented
@parkand1 can you fix the conflicts and use the new approach for the patterns that I described on the last meeting.
Here is the new flow: https://github.com/aws-samples/cdk-eks-blueprints-patterns#new-patterns

2023-05-19 19:16 UTC, parkand1 requested changes

2023-05-19 19:16 UTC, parkand1 commented on docs/patterns/security/securityhub.md
> +### View Critical and Failed Security Standards Controls findings
Can we add a section that walks the user on how to invoke a security event? As of right now, we are asking users to enable security hub but then are assuming that they already have guardduty and its runtime feature enabled. Maybe we add a bullet under the prerequisites that calls out that guardduty should be enabled

2023-05-23 17:16 UTC, shapirov103 reviewed
Added a few comments, please take a look @sbollers

2023-05-23 17:16 UTC, shapirov103 commented on docs/patterns/security/securityhub.md
> +To list the critical and faild security standards controls findings in the same account and region, run the following command:
minor: type faild

2023-05-23 18:17 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +### View Critical and Failed Security Standards Controls findings
The problem is that it will take time for GuardDuty findings to make their way into Security Hub. Instead I have them looking for findings from the Security Hub security standard controls which are failed, and any other Critical findings.

2023-05-23 18:31 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +npx cdk deploy securityhub-setup
I've made the update to deploy the pattern. 
For this pattern it doesn't seem to make sense to deploy a cluster. Security Hub is a place to collect findings across the AWS footprint from services that integrate with it. EKS doesn't integrate with it like GuardDuty does.

2023-05-24 00:25 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +The pattern will enable Security Hub in the `CDKCDK_DEFAULT_ACCOUNT` and `CDK_DEFAULT_REGION`, but only if it is not already enabled. If Security Hub is already enabled in the target AWS account and
Ack. Fixed in the local. Will include in next push.

2023-05-24 00:33 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +npx cdk deploy securityhub-setup
There is nothing to demonstrate except findings in Security Hub. Once the GuardDuty, Inspector, or other patterns are deployed they will generate EKS or container image related findings. Security Hub does not natively pickup EKS findings other than maybe Systems Manager findings for the EC2 nodes that the cluster runs on. The business stakeholders requested that we create a pattern to activate Security Hub which allowing the other patterns to send findings there which happens by default.

2023-05-24 01:19 UTC, sbollers commented on lib/security/securityhub-construct/securityhub-setup.ts
> +//import { aws_config as config } from 'aws-cdk-lib';
I am not seeing any lint warnings in vscode with the TSlint plugin.

2023-05-24 14:24 UTC, shapirov103 reviewed
Please see my comments

2023-05-24 14:24 UTC, shapirov103 commented on docs/patterns/security/securityhub.md
> +The blueprint deploys a sample GitOps workload.
Does it?

2023-05-24 14:24 UTC, shapirov103 commented on docs/patterns/security/securityhub.md
> +If you have deployed the [Amazon GuardDuty Protection EKS Blueprints pattern](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/security/guardduty.md) to the same acc
Minor: spelling PrivliegedContainer. Also why is it one word?

2023-05-24 14:24 UTC, shapirov103 commented on lib/security/securityhub-construct/index.ts
> +  blueprints.EksBlueprint.builder()
Not addressed?

2023-05-31 19:43 UTC, elamaran11 reviewed
Steve. Please fix the pointed issues. Mainly doc is missing pre req for running a cdk stack. Plus i see few typos which be fixed.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/guardduty.md
I was trying to run GuardDuty first. I think when i went with `make pattern` command, it didnt work because there is no instructions to do `npm i`, `cdk bootstrap` etc. So as a first user a customer will struggle with that.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/guardduty.md
https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/kubeflow.md This is a good example for pre req, npm i, bootstrap etc etc

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +1. Follow the usage [instructions](README.md#usage) to install the dependencies
the ordering is not correct. 1,2,3 :)
Also i do see instructions for `cdk bootstrap` or `npm i` will be difficult for first time user.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +Now you can check that the is successfully enabled in the by using the aws CLI to query the same account and region.
Grammer issue `that the is` ...

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +Now you can check that the is successfully enabled in the by using the aws CLI to query the same account and region.
`in the by using the aws CLI ` does not make sense.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +Now you can check that the is successfully enabled in the by using the aws CLI to query the same account and region.
AWS should be all caps.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +Using the aws CLI run following command in the same account and region where you deployed the stack.
AWS CLI, run...

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +The findings that you see in Security Hub will depend what you have configured in your account and region. In this example we deployed the [GuardDuty EKS blueprint](guardduty.md), the [Security Best
config?

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +The findings that you see in Security Hub will depend what you have configured in your account and region. In this example we deployed the [GuardDuty EKS blueprint](guardduty.md), the [Security Best
it should be `security`

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +To see any findings generated by GuardDuty in Security Hub, run the following command. If you completed the threat detection seciton of this module then you should have at least one.
section?
of this module. Which module?

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/eks-config-rules.md
> +1. Clone the repository.
numbering is not correct.

2023-05-31 19:43 UTC, elamaran11 commented on docs/patterns/security/eks-config-rules.md
> +1. Clone the repository.
Same feedback as other docs. You should have documentation similar to Kubeflow which shows pre req like `npm i`, `cdk bootstrap` etc.

2023-05-31 19:43 UTC, elamaran11 reviewed
Steve. Please fix the pointed issues. Mainly doc is missing pre req for running a cdk stack. Plus i see few typos which be fixed.

2023-05-31 21:21 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +1. Follow the usage [instructions](README.md#usage) to install the dependencies
The 1. 1. 1. is how you do an ordered list in markdown.
The README.md#usage coversd those instructions.

2023-05-31 21:24 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +Now you can check that the is successfully enabled in the by using the aws CLI to query the same account and region.
Addressed.

2023-05-31 21:29 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +The findings that you see in Security Hub will depend what you have configured in your account and region. In this example we deployed the [GuardDuty EKS blueprint](guardduty.md), the [Security Best
Yes, in the Deploy step we have them setup the Config managed rules for EKS security best practices.

2023-05-31 21:30 UTC, sbollers commented on docs/patterns/security/securityhub.md
> +To see any findings generated by GuardDuty in Security Hub, run the following command. If you completed the threat detection seciton of this module then you should have at least one.
The security module, which is the same one that the user is working through.

2023-05-31 21:32 UTC, elamaran11 commented on docs/patterns/security/securityhub.md
> +    "HubArn": "arn:aws:securityhub:us-east-1:XXXXXXXXXXXX:hub/default",
```
{
    "HubArn": "arn:aws:securityhub:us-east-1:940019131157:hub/default",
    "SubscribedAt": "2023-05-31T21:23:09.026Z",
    "AutoEnableControls": true,
    "ControlFindingGenerator": "SECURITY_CONTROL"
}

```
this is the output i got for this command.

2023-06-01 13:16 UTC, elamaran11 commented
Hi @sbollers As per our chat, Please fix the below comments, we can take a look again and will run. LGTM on the config setup class changes. Nice work.

1. Check on the [Kubeflow doc](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/kubeflow.md) and follow on how kubeconfig update is handled and copy paste the same to GuardDuty doc.
2. Check on [deploy resources section on Kubeflow doc](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/kubeflow.md#deploy-eks-cluster-with-amazon-eks-blueprints-for-cdk) and copy paste how npm install, clone etc etc is handled and do the same on all three docs - GD, SecHub and config.

2023-06-01 22:23 UTC, elamaran11 approved these changes
LGTM

2023-06-01 22:34 UTC, parkand1 approved these changes
LGTM

2023-06-01 22:34 UTC, merged